// Code generated by Icestudio 0.5.1n210107

`default_nettype none

//---- Top entity
module main #(
 parameter v59c3e1 = "v59c3e1.list",
 parameter v5677c1 = 7,
 parameter v15e8cc = 10
) (
 input v4c2cd3,
 input vf1d4a4,
 input v10e21b,
 input v9cd28c,
 input vclk,
 output vbac517,
 output [1:0] v158c4e,
 output vfdf7eb,
 output [3:0] v418660,
 output [1:0] v58f23a,
 output [0:3] vinit
);
 localparam p3 = v5677c1;
 localparam p6 = v15e8cc;
 localparam p7 = v59c3e1;
 wire [0:3] w0;
 wire [0:3] w1;
 wire w2;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w8;
 wire [0:1] w9;
 wire [0:1] w10;
 wire [0:1] w11;
 wire [0:1] w12;
 wire [0:1] w13;
 wire w14;
 wire w15;
 wire w16;
 wire w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 wire w22;
 wire w23;
 wire [0:1] w24;
 wire [0:4] w25;
 wire w26;
 wire w27;
 wire w28;
 wire w29;
 wire w30;
 wire w31;
 wire w32;
 wire w33;
 wire w34;
 wire w35;
 wire w36;
 assign v418660 = w8;
 assign v158c4e = w9;
 assign v58f23a = w13;
 assign vbac517 = w14;
 assign vfdf7eb = w15;
 assign w16 = v4c2cd3;
 assign w17 = v10e21b;
 assign w18 = vf1d4a4;
 assign w19 = v9cd28c;
 assign w31 = vclk;
 assign w32 = vclk;
 assign w8 = w0;
 assign w32 = w31;
 assign w36 = w35;
 vd3fb4e v54a385 (
  .v2978f0(w10)
 );
 vdb2de9 vb3ffb8 (
  .v8b7d6a(w0),
  .v05f1f3(w20),
  .v151a08(w21),
  .vb38241(w22),
  .va091a3(w23)
 );
 vaac742 vb4cbe1 (
  .v66e00f(w1),
  .v3d694d(w2),
  .v209dc0(w31),
  .vbf042c(w34)
 );
 v9274d3 #(
  .vc5c8ea(p3)
 ) v297590 (
  .v00a92d(w1)
 );
 v725b7e v3ce46f (
  .v9fb85f(w2)
 );
 vaac742 v2df4e4 (
  .v3d694d(w4),
  .v66e00f(w5),
  .v209dc0(w32),
  .vbf042c(w33)
 );
 v725b7e vc85215 (
  .v9fb85f(w4)
 );
 v9274d3 #(
  .vc5c8ea(p6)
 ) vbc799f (
  .v00a92d(w5)
 );
 veebee1 v9d482e (
  .v7fb9b3(w9),
  .vc9d156(w10),
  .v340b68(w11),
  .v50d6c6(w27)
 );
 v945d5c va81c18 (
  .v2978f0(w11)
 );
 veebee1 v8000f5 (
  .v340b68(w12),
  .v7fb9b3(w13),
  .vc9d156(w24),
  .v50d6c6(w29)
 );
 v945d5c va1f405 (
  .v2978f0(w12)
 );
 vb2090f vc45951 (
  .vcbab45(w14),
  .v3ca442(w26),
  .v0e28cb(w35)
 );
 vb2090f vcc5c7d (
  .vcbab45(w15),
  .v3ca442(w28),
  .v0e28cb(w36)
 );
 v35f267 v5b879e (
  .v0e28cb(w16),
  .vcbab45(w20)
 );
 v35f267 v20e1e6 (
  .v0e28cb(w17),
  .vcbab45(w22)
 );
 v35f267 v8d0df1 (
  .v0e28cb(w18),
  .vcbab45(w21)
 );
 v35f267 v02d283 (
  .v0e28cb(w19),
  .vcbab45(w23)
 );
 v5cc6ec vcbb706 (
  .v50d6c6(w30),
  .vb186da(w33),
  .v381ebf(w34),
  .vc93bbe(w35)
 );
 vd3fb4e v19eb66 (
  .v2978f0(w24)
 );
 vb4c12b #(
  .vb36a78(p7)
 ) v7dc3b1 (
  .v851180(w0),
  .vfde47f(w25)
 );
 v4798ba v9c0661 (
  .v2f7f3b(w25),
  .va8081e(w26),
  .v84e765(w27),
  .v185257(w28),
  .ve17a78(w29),
  .v6c3ff1(w30)
 );
 assign vinit = 4'b0000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module vd3fb4e #(
 parameter vfffc23 = 1
) (
 output [1:0] v2978f0
);
 localparam p1 = vfffc23;
 wire [0:1] w0;
 assign v2978f0 = w0;
 v157753 #(
  .vc5c8ea(p1)
 ) v335745 (
  .v4ffce0(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_1_2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 1 para bus de 2 bits
/*-------------------------------------------------*/
//---- Top entity
module v157753 #(
 parameter vc5c8ea = 0
) (
 output [1:0] v4ffce0
);
 localparam p1 = vc5c8ea;
 wire [0:1] w0;
 assign v4ffce0 = w0;
 v157753_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 2 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v157753_v465065 #(
 parameter VALUE = 0
) (
 output [1:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module vdb2de9 (
 input v05f1f3,
 input v151a08,
 input vb38241,
 input va091a3,
 output [3:0] v8b7d6a
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = va091a3;
 assign w1 = vb38241;
 assign w2 = v151a08;
 assign w3 = v05f1f3;
 assign v8b7d6a = w4;
 vdb2de9_v1d17f3 v1d17f3 (
  .i0(w0),
  .i1(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Agregador-bus4  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 4 bits a bus de 4-bits
/*-------------------------------------------------*/

module vdb2de9_v1d17f3 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
endmodule
//---- Top entity
module vaac742 (
 input v209dc0,
 input [3:0] v66e00f,
 input v3d694d,
 output vbf042c
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:3] w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 wire [0:3] w12;
 wire [0:3] w13;
 wire w14;
 wire w15;
 wire [0:3] w16;
 wire [0:3] w17;
 wire w18;
 wire w19;
 wire w20;
 wire w21;
 assign w5 = v66e00f;
 assign w6 = v209dc0;
 assign w7 = v209dc0;
 assign w8 = v209dc0;
 assign w9 = v209dc0;
 assign w10 = v3d694d;
 assign vbf042c = w11;
 assign w13 = v66e00f;
 assign w17 = v66e00f;
 assign w4 = w0;
 assign w7 = w6;
 assign w8 = w6;
 assign w8 = w7;
 assign w9 = w6;
 assign w9 = w7;
 assign w9 = w8;
 assign w13 = w5;
 assign w14 = w0;
 assign w14 = w4;
 assign w17 = w5;
 assign w17 = w13;
 vc77d0f v1c0d65 (
  .v36cd15(w0),
  .v20f691(w1),
  .vebeff4(w3),
  .v08dbc1(w5),
  .v9e2649(w6)
 );
 v880eeb vdd18ab (
  .vd06c53(w0),
  .v572c59(w1),
  .vc33bc3(w2),
  .vb27d62(w8)
 );
 vbafc77 v818879 (
  .v311114(w2),
  .v261eba(w9)
 );
 va4d0f7 v34bc3c (
  .v311114(w3),
  .v1f314e(w4),
  .v261eba(w7)
 );
 v91abf1 vb65ef0 (
  .vcdeb69(w10),
  .v09a613(w11),
  .v695853(w19)
 );
 vaa522b vac10e8 (
  .vf3f282(w12)
 );
 vc9d38c v5369c6 (
  .v72a4a4(w12),
  .vde0299(w13),
  .v97b3a2(w15)
 );
 v91abf1 v2924a9 (
  .v695853(w14),
  .vcdeb69(w15),
  .v09a613(w18)
 );
 v1ffaea va5c3c3 (
  .vf3f282(w16)
 );
 va27ebf v895c27 (
  .v240f0a(w18),
  .vdcf411(w19),
  .v02803c(w20),
  .v7e3c7c(w21)
 );
 v69917e va81b8d (
  .vad6846(w16),
  .v199867(w17),
  .v6f3b5f(w20)
 );
 v725b7e ve68c73 (
  .v9fb85f(w21)
 );
endmodule

/*-------------------------------------------------*/
/*-- PWM-mbot-25Khz  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Unidad PWM con velocidades 1 - 9. Frec. 25Khz
/*-------------------------------------------------*/
//---- Top entity
module vc77d0f (
 input v9e2649,
 input vebeff4,
 input v36cd15,
 input [3:0] v08dbc1,
 output [3:0] v7e8fb6,
 output v20f691
);
 wire w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:3] w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v20f691 = w0;
 assign w1 = v08dbc1;
 assign v7e8fb6 = w3;
 assign w4 = v9e2649;
 assign w5 = vebeff4;
 assign w7 = v36cd15;
 assign w3 = w2;
 assign w6 = w0;
 v69917e v060374 (
  .v6f3b5f(w0),
  .vad6846(w1),
  .v199867(w2)
 );
 v33cc14 v154c7e (
  .v7e8fb6(w2),
  .v9e2649(w4),
  .vfda572(w5),
  .v80c217(w6),
  .v4324b8(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-4-M-ena-cnt  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador ascendente de 4bits, modulo M, con entrada de cuenta y enable
/*-------------------------------------------------*/
//---- Top entity
module v69917e (
 input [3:0] v199867,
 input [3:0] vad6846,
 output v6f3b5f
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:3] w3;
 wire [0:1] w4;
 wire [0:1] w5;
 wire [0:3] w6;
 wire [0:1] w7;
 wire [0:1] w8;
 assign v6f3b5f = w0;
 assign w3 = v199867;
 assign w6 = vad6846;
 v91abf1 vde6d49 (
  .v09a613(w0),
  .v695853(w1),
  .vcdeb69(w2)
 );
 v48f62b v3555c1 (
  .v6f3b5f(w1),
  .v14aeed(w4),
  .vbd1653(w8)
 );
 v48f62b v3da6b7 (
  .v6f3b5f(w2),
  .v14aeed(w5),
  .vbd1653(w7)
 );
 v4ecca6 v76a5ca (
  .v21a753(w3),
  .v9e4a4a(w4),
  .vf24fb3(w5)
 );
 v4ecca6 v62a0b1 (
  .v21a753(w6),
  .vf24fb3(w7),
  .v9e4a4a(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- eq-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de igualdad para números de 4 bit
/*-------------------------------------------------*/
//---- Top entity
module v91abf1 (
 input v695853,
 input vcdeb69,
 output v09a613
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign v09a613 = w0;
 assign w2 = v695853;
 assign w3 = vcdeb69;
 v4b9553 v3d9ac5 (
  .vcbab45(w1),
  .v0e28cb(w2),
  .v3ca442(w3)
 );
 v0ec077 vfc842e (
  .v25ee73(w0),
  .v4b5bc2(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Puerta-AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND
/*-------------------------------------------------*/
//---- Top entity
module v4b9553 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v4b9553_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
 v44391c vf4114c (
 
 );
 v44391c vec8c80 (
 
 );
endmodule

/*-------------------------------------------------*/
/*-- NAND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- NAND logic gate
/*-------------------------------------------------*/

module v4b9553_vf4938a (
 input a,
 input b,
 output c
);
 // NAND logic gate
 
 assign c = ~(a & b);
endmodule
//---- Top entity
module v44391c
;
 v74d69b v949c82 (
 
 );
 v74d69b ve0f5c7 (
 
 );
endmodule

/*-------------------------------------------------*/
/*-- Transistor-mosfet  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Transistor
/*-------------------------------------------------*/
//---- Top entity
module v74d69b
;
 vef9670 vdb7477 (
 
 );
 vef9670 v826842 (
 
 );
 vef9670 vdc9b55 (
 
 );
 vef9670 vea688b (
 
 );
endmodule

/*-------------------------------------------------*/
/*-- semiconductores  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Transistor cmos hecho a partir de semiconductores
/*-------------------------------------------------*/
//---- Top entity
module vef9670
;
 v8450b0 vd09707 (
 
 );
 v8450b0 v38def6 (
 
 );
 v8450b0 v0c6e31 (
 
 );
 v8450b0 v3071e7 (
 
 );
 v8450b0 vca3873 (
 
 );
endmodule

/*-------------------------------------------------*/
/*-- Cristal-si  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Cristal de Siicio
/*-------------------------------------------------*/
//---- Top entity
module v8450b0
;

endmodule

/*-------------------------------------------------*/
/*-- Atomo-si  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Atomos de silicio
/*-------------------------------------------------*/
//---- Top entity
module v0ec077 (
 input v4b5bc2,
 output v25ee73
);
 wire w0;
 wire w1;
 wire w2;
 assign v25ee73 = w0;
 assign w1 = v4b5bc2;
 assign w2 = v4b5bc2;
 assign w2 = w1;
 v4b9553 vdf6feb (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Puerta-not  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/
//---- Top entity
module v48f62b (
 input [1:0] v14aeed,
 input [1:0] vbd1653,
 output v6f3b5f
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:1] w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire w7;
 wire w8;
 assign v6f3b5f = w0;
 assign w3 = v14aeed;
 assign w6 = vbd1653;
 vfb8c65 ve06f73 (
  .v195d0b(w1),
  .v3105e5(w4),
  .vb1f92b(w7)
 );
 vfb8c65 vcbda0d (
  .v195d0b(w2),
  .v3105e5(w5),
  .vb1f92b(w8)
 );
 v91abf1 vde6d49 (
  .v09a613(w0),
  .v695853(w1),
  .vcdeb69(w2)
 );
 v28a281 va8d027 (
  .vc9d8af(w3),
  .v26347c(w4),
  .vc266df(w5)
 );
 v28a281 vcd3412 (
  .vc9d8af(w6),
  .v26347c(w7),
  .vc266df(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- eq-2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de igualdad para números de 2 bit
/*-------------------------------------------------*/
//---- Top entity
module vfb8c65 (
 input v3105e5,
 input vb1f92b,
 output v195d0b
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v3105e5;
 assign w1 = vb1f92b;
 assign v195d0b = w3;
 v3dfc1e v5ac440 (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 v0ec077 v0a59f4 (
  .v4b5bc2(w2),
  .v25ee73(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- eq-1bitt  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comparador de igualdad para números de 1 bit
/*-------------------------------------------------*/
//---- Top entity
module v3dfc1e (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign vcbab45 = w0;
 assign w1 = v0e28cb;
 assign w2 = v3ca442;
 assign w4 = v3ca442;
 assign w8 = v0e28cb;
 assign w4 = w2;
 assign w8 = w1;
 v4b9553 vc87175 (
  .vcbab45(w0),
  .v0e28cb(w5),
  .v3ca442(w6)
 );
 v0ec077 v3ca685 (
  .v4b5bc2(w1),
  .v25ee73(w3)
 );
 v0ec077 vc544fc (
  .v4b5bc2(w2),
  .v25ee73(w7)
 );
 v4b9553 v17c8f6 (
  .v0e28cb(w3),
  .v3ca442(w4),
  .vcbab45(w5)
 );
 v4b9553 v3e587c (
  .vcbab45(w6),
  .v3ca442(w7),
  .v0e28cb(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- XOR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- XOR logic gate
/*-------------------------------------------------*/
//---- Top entity
module v28a281 (
 input [1:0] vc9d8af,
 output v26347c,
 output vc266df
);
 wire [0:1] w0;
 wire w1;
 wire w2;
 assign w0 = vc9d8af;
 assign v26347c = w1;
 assign vc266df = w2;
 v28a281_v89b409 v89b409 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Split2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 2bits
/*-------------------------------------------------*/

module v28a281_v89b409 (
 input [1:0] i,
 output o1,
 output o0
);
 assign {o1,o0} = i;
 
 
endmodule
//---- Top entity
module v4ecca6 (
 input [3:0] v21a753,
 output [1:0] v9e4a4a,
 output [1:0] vf24fb3
);
 wire [0:3] w0;
 wire [0:1] w1;
 wire [0:1] w2;
 assign w0 = v21a753;
 assign v9e4a4a = w1;
 assign vf24fb3 = w2;
 v4ecca6_v89b409 v89b409 (
  .i(w0),
  .o1(w1),
  .o0(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Split-2-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 4bits en 2 (2 + 2)
/*-------------------------------------------------*/

module v4ecca6_v89b409 (
 input [3:0] i,
 output [1:0] o1,
 output [1:0] o0
);
 assign {o1,o0} = i;
 
 
endmodule
//---- Top entity
module v33cc14 (
 input v9e2649,
 input vfda572,
 input v4324b8,
 input v80c217,
 output [3:0] v7e8fb6
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:3] w3;
 wire [0:3] w4;
 wire [0:3] w5;
 wire w6;
 wire w7;
 assign w0 = vfda572;
 assign w1 = v4324b8;
 assign v7e8fb6 = w4;
 assign w6 = v80c217;
 assign w7 = v9e2649;
 assign w4 = w3;
 v990584 vbe113e (
  .vd390a5(w3),
  .vc6b1bf(w5)
 );
 v91abf1 v3e31e4 (
  .v695853(w0),
  .vcdeb69(w1),
  .v09a613(w2)
 );
 v4b7546 v1df151 (
  .v0421e9(w2),
  .v1b9edf(w3),
  .v2a4745(w5),
  .v1f71b2(w6),
  .ve386ea(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Contador-4-cnt-ena-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Contador ascendente de 4bits, con entrada de cuenta, enable y reset síncrono
/*-------------------------------------------------*/
//---- Top entity
module v990584 (
 input [3:0] vd390a5,
 output [3:0] vc6b1bf
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 assign vc6b1bf = w0;
 assign w1 = vd390a5;
 ve2c56e v5cd7d1 (
  .v504ed5(w0),
  .v39c767(w1),
  .v40c2be(w2)
 );
 v318d43 v245f63 (
  .vf3f282(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Inc-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Incrementar en 1 el dato de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module ve2c56e (
 input [3:0] v39c767,
 input [3:0] v40c2be,
 output ve259b1,
 output [3:0] v504ed5
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire w2;
 wire [0:3] w3;
 wire w4;
 assign w0 = v39c767;
 assign w1 = v40c2be;
 assign v504ed5 = w3;
 assign ve259b1 = w4;
 v1ceeb3 v88a745 (
  .v39c767(w0),
  .v40c2be(w1),
  .v3582e1(w2),
  .v504ed5(w3),
  .ve259b1(w4)
 );
 v21cfcc v7e040b (
  .v9fb85f(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sumador-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de 4 bits con acarreo de salida
/*-------------------------------------------------*/
//---- Top entity
module v1ceeb3 (
 input [3:0] v39c767,
 input [3:0] v40c2be,
 input v3582e1,
 output ve259b1,
 output [3:0] v504ed5
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:3] w2;
 wire [0:1] w3;
 wire [0:1] w4;
 wire [0:1] w5;
 wire w6;
 wire [0:1] w7;
 wire [0:1] w8;
 wire w9;
 wire w10;
 wire [0:1] w11;
 assign v504ed5 = w0;
 assign w1 = v39c767;
 assign w2 = v40c2be;
 assign w9 = v3582e1;
 assign ve259b1 = w10;
 v4ecca6 v18a070 (
  .v21a753(w1),
  .v9e4a4a(w5),
  .vf24fb3(w7)
 );
 v4ecca6 v4d4f5f (
  .v21a753(w2),
  .v9e4a4a(w4),
  .vf24fb3(w8)
 );
 v42d6b1 v9c756d (
  .vadf1ad(w0),
  .vd1b8eb(w3),
  .v0e5c05(w11)
 );
 v90f305 v771b43 (
  .vd1dd06(w3),
  .v9f023c(w4),
  .v40d3be(w5),
  .v3582e1(w6),
  .ve259b1(w10)
 );
 v90f305 ve46001 (
  .ve259b1(w6),
  .v40d3be(w7),
  .v9f023c(w8),
  .v3582e1(w9),
  .vd1dd06(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sumador-4bits-cin  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de 4 bits con acarreo de salida y de entrada
/*-------------------------------------------------*/
//---- Top entity
module v42d6b1 (
 input [1:0] vd1b8eb,
 input [1:0] v0e5c05,
 output [3:0] vadf1ad
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire [0:3] w2;
 assign w0 = vd1b8eb;
 assign w1 = v0e5c05;
 assign vadf1ad = w2;
 v42d6b1_v89b409 v89b409 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Join2-2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 buses (2+2)  a bus de 4bits
/*-------------------------------------------------*/

module v42d6b1_v89b409 (
 input [1:0] i1,
 input [1:0] i0,
 output [3:0] o
);
 assign o = {i1,i0};
 
 
endmodule
//---- Top entity
module v90f305 (
 input [1:0] v40d3be,
 input [1:0] v9f023c,
 input v3582e1,
 output ve259b1,
 output [1:0] vd1dd06
);
 wire w0;
 wire w1;
 wire w2;
 wire [0:1] w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire w7;
 wire w8;
 wire [0:1] w9;
 wire w10;
 wire w11;
 assign w0 = v3582e1;
 assign ve259b1 = w1;
 assign w3 = v40d3be;
 assign w6 = v9f023c;
 assign vd1dd06 = w9;
 vaf0ab1 vd698f6 (
  .v45b85e(w0),
  .v3fb1ac(w2),
  .v3a02f3(w5),
  .v6fe456(w8),
  .v8da78a(w11)
 );
 vaf0ab1 v877678 (
  .v3fb1ac(w1),
  .v45b85e(w2),
  .v3a02f3(w4),
  .v6fe456(w7),
  .v8da78a(w10)
 );
 v28a281 v03d607 (
  .vc9d8af(w3),
  .v26347c(w4),
  .vc266df(w5)
 );
 v28a281 v07fe38 (
  .vc9d8af(w6),
  .v26347c(w7),
  .vc266df(w8)
 );
 vc67fda v80475d (
  .v16058a(w9),
  .v29d743(w10),
  .v4d8fdf(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sumador-2bits-cin  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de 2 bits con acarreo de salida y de entrada
/*-------------------------------------------------*/
//---- Top entity
module vaf0ab1 (
 input v3a02f3,
 input v6fe456,
 input v45b85e,
 output v3fb1ac,
 output v8da78a
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign v3fb1ac = w0;
 assign w2 = v45b85e;
 assign v8da78a = w3;
 assign w6 = v3a02f3;
 assign w7 = v6fe456;
 v493ea8 va64435 (
  .vcbab45(w0),
  .v3ca442(w1),
  .v0e28cb(w5)
 );
 v2177b1 v02bbca (
  .v8aaf0c(w1),
  .vd24b39(w2),
  .v274c0e(w3),
  .v48c82f(w4)
 );
 v2177b1 v9689e2 (
  .v274c0e(w4),
  .v8aaf0c(w5),
  .v48c82f(w6),
  .vd24b39(w7)
 );
endmodule

/*-------------------------------------------------*/
/*-- Sumador-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Sumador de 1bit, con arraceo de entrada y salida
/*-------------------------------------------------*/
//---- Top entity
module v493ea8 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v0ec077 v1a413a (
  .v4b5bc2(w0),
  .v25ee73(w3)
 );
 v0ec077 v6168dd (
  .v4b5bc2(w1),
  .v25ee73(w4)
 );
 v4b9553 vdb792a (
  .vcbab45(w2),
  .v0e28cb(w3),
  .v3ca442(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- OR  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta OR
/*-------------------------------------------------*/
//---- Top entity
module v2177b1 (
 input v48c82f,
 input vd24b39,
 output v8aaf0c,
 output v274c0e
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign v8aaf0c = w0;
 assign w1 = v48c82f;
 assign w2 = vd24b39;
 assign v274c0e = w3;
 assign w4 = vd24b39;
 assign w5 = v48c82f;
 assign w4 = w2;
 assign w5 = w1;
 v91abf1 v9da6eb (
  .v09a613(w0),
  .v695853(w1),
  .vcdeb69(w2)
 );
 v3dfc1e v5fe03f (
  .vcbab45(w3),
  .v3ca442(w4),
  .v0e28cb(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Semi-sumador  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Semisumador. 2 bits de entrada, saca la suma (S) y el acarreo (C)
/*-------------------------------------------------*/
//---- Top entity
module vc67fda (
 input v29d743,
 input v4d8fdf,
 output [1:0] v16058a
);
 wire w0;
 wire w1;
 wire [0:1] w2;
 assign w0 = v29d743;
 assign w1 = v4d8fdf;
 assign v16058a = w2;
 vc67fda_v89b409 v89b409 (
  .i1(w0),
  .i0(w1),
  .o(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Join2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Agregador de 2 cables a bus de 2bits
/*-------------------------------------------------*/

module vc67fda_v89b409 (
 input i1,
 input i0,
 output [1:0] o
);
 assign o = {i1,i0};
 
 
endmodule
//---- Top entity
module v21cfcc (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v21cfcc_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 0
/*-------------------------------------------------*/

module v21cfcc_vb2eccd (
 output q
);
 //-- Bit constante a 0
 assign q = 1'b0;
 
 
endmodule
//---- Top entity
module v318d43 #(
 parameter vfffc23 = 4'h1
) (
 output [3:0] vf3f282
);
 localparam p1 = vfffc23;
 wire [0:3] w0;
 assign vf3f282 = w0;
 v818f71 #(
  .vc5c8ea(p1)
 ) v0a5630 (
  .v00a92d(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_1_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 1 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v818f71 #(
 parameter vc5c8ea = 4'h0
) (
 output [3:0] v00a92d
);
 localparam p0 = vc5c8ea;
 wire [0:3] w1;
 assign v00a92d = w1;
 v818f71_v465065 #(
  .V(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante de 4 bits
/*-------------------------------------------------*/

module v818f71_v465065 #(
 parameter V = 0
) (
 output [3:0] k
);
 assign k = V;
endmodule
//---- Top entity
module v4b7546 (
 input ve386ea,
 input [3:0] v2a4745,
 input v0421e9,
 input v1f71b2,
 output [3:0] v1b9edf
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire w2;
 wire [0:1] w3;
 wire w4;
 wire w5;
 wire [0:1] w6;
 wire [0:1] w7;
 wire [0:1] w8;
 wire w9;
 wire w10;
 wire w11;
 assign v1b9edf = w0;
 assign w1 = v2a4745;
 assign w2 = ve386ea;
 assign w4 = v0421e9;
 assign w5 = v1f71b2;
 assign w9 = ve386ea;
 assign w10 = v1f71b2;
 assign w11 = v0421e9;
 assign w9 = w2;
 assign w10 = w5;
 assign w11 = w4;
 v42d6b1 v6c11fe (
  .vadf1ad(w0),
  .vd1b8eb(w6),
  .v0e5c05(w7)
 );
 v4ecca6 v9f2866 (
  .v21a753(w1),
  .v9e4a4a(w3),
  .vf24fb3(w8)
 );
 v8a1038 v135190 (
  .ve386ea(w2),
  .vaf74f8(w3),
  .v1c1e38(w4),
  .v2ab36b(w5),
  .v45c976(w6)
 );
 v8a1038 v55f5e9 (
  .v45c976(w7),
  .vaf74f8(w8),
  .ve386ea(w9),
  .v2ab36b(w10),
  .v1c1e38(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Reg4-rst-load  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 4 bits con reset síncrono y entrada de load
/*-------------------------------------------------*/
//---- Top entity
module v8a1038 (
 input ve386ea,
 input [1:0] vaf74f8,
 input v1c1e38,
 input v2ab36b,
 output [1:0] v45c976
);
 wire [0:1] w0;
 wire [0:1] w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 wire w11;
 assign v45c976 = w0;
 assign w1 = vaf74f8;
 assign w2 = ve386ea;
 assign w5 = v2ab36b;
 assign w6 = v1c1e38;
 assign w8 = ve386ea;
 assign w10 = v1c1e38;
 assign w11 = v2ab36b;
 assign w8 = w2;
 assign w10 = w6;
 assign w11 = w5;
 vc67fda v7e92b5 (
  .v16058a(w0),
  .v29d743(w3),
  .v4d8fdf(w9)
 );
 v28a281 v684f72 (
  .vc9d8af(w1),
  .v26347c(w4),
  .vc266df(w7)
 );
 vf07043 vdffc5f (
  .vb27d62(w2),
  .vd06c53(w3),
  .v9066c2(w4),
  .v572c59(w5),
  .vc33bc3(w6)
 );
 vf07043 v0480d8 (
  .v9066c2(w7),
  .vb27d62(w8),
  .vd06c53(w9),
  .vc33bc3(w10),
  .v572c59(w11)
 );
endmodule

/*-------------------------------------------------*/
/*-- Reg2  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Registro de 2 bits, con load y reset síncrono
/*-------------------------------------------------*/
//---- Top entity
module vf07043 #(
 parameter v4d7602 = 0
) (
 input vb27d62,
 input v9066c2,
 input vc33bc3,
 input v572c59,
 output vd06c53
);
 localparam p1 = v4d7602;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign vd06c53 = w0;
 assign w2 = vb27d62;
 assign w3 = v9066c2;
 assign w4 = vc33bc3;
 assign w5 = v572c59;
 v60570e #(
  .vd93afa(p1)
 ) v6210b8 (
  .vef02d7(w0),
  .va44fe0(w2),
  .vc96ba8(w3),
  .vb24dd7(w4),
  .ve64610(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D-rst-ena-0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable D, con reset síncrono y enable, inicializado a 0
/*-------------------------------------------------*/
//---- Top entity
module v60570e #(
 parameter vd93afa = 0
) (
 input va44fe0,
 input vc96ba8,
 input vb24dd7,
 input ve64610,
 output vef02d7
);
 localparam p1 = vd93afa;
 localparam p6 = vd93afa;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w7;
 wire w8;
 wire w9;
 wire w10;
 assign vef02d7 = w0;
 assign w2 = va44fe0;
 assign w4 = ve64610;
 assign w8 = vb24dd7;
 assign w9 = vc96ba8;
 assign w10 = w0;
 v77050b #(
  .v38488b(p1)
 ) vcbf1f1 (
  .vc24d9f(w0),
  .vb55943(w2),
  .vef4cea(w3)
 );
 va27ebf v9e6bc0 (
  .vdcf411(w3),
  .v02803c(w4),
  .v7e3c7c(w5),
  .v240f0a(w7)
 );
 v3fcbec #(
  .va5aba0(p6)
 ) ve23275 (
  .v9b792b(w5)
 );
 v14041f v0a97d5 (
  .vdcf411(w7),
  .v02803c(w8),
  .v240f0a(w9),
  .v7e3c7c(w10)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D-ena-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable tipo D con entrada de reset y enable, inicializado al parámetro INI
/*-------------------------------------------------*/
//---- Top entity
module v77050b #(
 parameter v38488b = 0
) (
 input vb55943,
 input vef4cea,
 output vc24d9f
);
 localparam p3 = v38488b;
 wire w0;
 wire w1;
 wire w2;
 assign w0 = vef4cea;
 assign w1 = vb55943;
 assign vc24d9f = w2;
 v77050b_v526aa2 #(
  .DINI(p3)
 ) v526aa2 (
  .d(w0),
  .clk(w1),
  .q(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Flip-flop D  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable D con inicialización paramétrica
/*-------------------------------------------------*/

module v77050b_v526aa2 #(
 parameter DINI = 0
) (
 input clk,
 input d,
 output q
);
 // D flip-flop
 // parameter DINI = 0;
 
 reg q = DINI;
 
 always @(posedge clk)
   q <= d;
   
 
 
endmodule
//---- Top entity
module va27ebf (
 input v7e3c7c,
 input v240f0a,
 input v02803c,
 output vdcf411
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 assign vdcf411 = w0;
 assign w3 = v240f0a;
 assign w5 = v02803c;
 assign w6 = v7e3c7c;
 assign w7 = v02803c;
 assign w7 = w5;
 v493ea8 vc43974 (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 v91abf1 v2029a7 (
  .v09a613(w1),
  .v695853(w6),
  .vcdeb69(w7)
 );
 v0ec077 vee713b (
  .v25ee73(w4),
  .v4b5bc2(w5)
 );
 v91abf1 vcee616 (
  .v09a613(w2),
  .v695853(w3),
  .vcdeb69(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-2-1-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor 2:1 de 1-bit
/*-------------------------------------------------*/
//---- Top entity
module v3fcbec #(
 parameter va5aba0 = 0
) (
 output v9b792b
);
 localparam p0 = va5aba0;
 wire w1;
 assign v9b792b = w1;
 v3fcbec_v48515b #(
  .V(p0)
 ) v48515b (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Const-1bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Constante genérica de 1 bit
/*-------------------------------------------------*/

module v3fcbec_v48515b #(
 parameter V = 0
) (
 output k
);
 assign k = V;
 
endmodule
//---- Top entity
module v14041f (
 input v7e3c7c,
 input v240f0a,
 input v02803c,
 output vdcf411
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v02803c;
 assign w1 = v240f0a;
 assign w2 = v7e3c7c;
 assign vdcf411 = w3;
 va27ebf ve344b0 (
  .v02803c(w0),
  .v7e3c7c(w1),
  .v240f0a(w2),
  .vdcf411(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux-2-1-1bit-girado  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor 2:1 de 1-bit, girado
/*-------------------------------------------------*/
//---- Top entity
module v880eeb #(
 parameter v4d7602 = 0
) (
 input vb27d62,
 input vc33bc3,
 input v572c59,
 output vd06c53
);
 localparam p1 = v4d7602;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 assign vd06c53 = w0;
 assign w2 = vb27d62;
 assign w3 = vc33bc3;
 assign w4 = v572c59;
 v45cdc1 #(
  .vd93afa(p1)
 ) v243f26 (
  .vef02d7(w0),
  .va44fe0(w2),
  .vb24dd7(w3),
  .ve64610(w4)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D-set-rst-ena-0  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable D, con set y  reset, inicializado a 0
/*-------------------------------------------------*/
//---- Top entity
module v45cdc1 #(
 parameter vd93afa = 0
) (
 input va44fe0,
 input vb24dd7,
 input ve64610,
 output vef02d7
);
 localparam p1 = vd93afa;
 wire w0;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 wire w9;
 assign vef02d7 = w0;
 assign w2 = va44fe0;
 assign w5 = ve64610;
 assign w7 = vb24dd7;
 assign w9 = w0;
 v77050b #(
  .v38488b(p1)
 ) vb006fa (
  .vc24d9f(w0),
  .vb55943(w2),
  .vef4cea(w3)
 );
 va27ebf v4aaabe (
  .vdcf411(w3),
  .v7e3c7c(w4),
  .v02803c(w5),
  .v240f0a(w6)
 );
 v21cfcc vdc1bd4 (
  .v9fb85f(w4)
 );
 va27ebf vdf4374 (
  .vdcf411(w6),
  .v02803c(w7),
  .v7e3c7c(w8),
  .v240f0a(w9)
 );
 v725b7e v62fe00 (
  .v9fb85f(w8)
 );
endmodule

/*-------------------------------------------------*/
/*-- Biestable-D-set-rst  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Biestable tipo D con entradas de set y reset, inicializado al parámetro INI
/*-------------------------------------------------*/
//---- Top entity
module v725b7e (
 output v9fb85f
);
 wire w0;
 assign v9fb85f = w0;
 v725b7e_vb2eccd vb2eccd (
  .q(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Un bit constante a 1
/*-------------------------------------------------*/

module v725b7e_vb2eccd (
 output q
);
 //-- Bit constante a 1
 assign q = 1'b1;
 
 
endmodule
//---- Top entity
module vbafc77 (
 input v261eba,
 output v311114
);
 wire w0;
 wire w1;
 assign v311114 = w0;
 assign w1 = v261eba;
 vbafc77_v8ecb1f v8ecb1f (
  .o(w0),
  .clk(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Corazon-25KHz-40us-P  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Pulsos de anchura igual al relog del sistema y frecuencia de 25KHz (40us)
/*-------------------------------------------------*/

module vbafc77_v8ecb1f (
 input clk,
 output o
);
 //-- Constante para dividir y obtener una señal
 //-- de frecuencia de 25KHz (40us)
 
 localparam M = 481;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 reg o;  //-- output signal
 
 always @(posedge clk)
     if (divcounter == M-1) begin
       o <= 1;
       divcounter = 0;
     end 
     else begin
       divcounter <=  divcounter + 1;
       o <= 0;
     end  
   
     
 
 
endmodule
//---- Top entity
module va4d0f7 (
 input v261eba,
 input v1f314e,
 output v311114
);
 wire w0;
 wire w1;
 wire w2;
 assign v311114 = w0;
 assign w1 = v261eba;
 assign w2 = v1f314e;
 va4d0f7_v8ecb1f v8ecb1f (
  .o(w0),
  .clk(w1),
  .ena(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- Corazon-25KHz-40us-P  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Pulsos de anchura igual al relog del sistema y frecuencia de 25KHz (40us)
/*-------------------------------------------------*/

module va4d0f7_v8ecb1f (
 input clk,
 input ena,
 output o
);
 //-- Constante para dividir y obtener una señal
 //-- de frecuencia de 250KHz (4us)
 
 localparam M = 49;
 
 //-- Calcular el numero de bits para almacenar M
 localparam N = $clog2(M);
 
 //-- Registro del divisor
 reg [N-1:0] divcounter;
 
 reg o;  //-- output signal
 
 always @(posedge clk)
   if (ena)
     if (divcounter == M-1) begin
       o <= 1;
       divcounter = 0;
     end 
     else begin
       divcounter <=  divcounter + 1;
       o <= 0;
     end
   else
     divcounter <= 0;
   
     
 
 
endmodule
//---- Top entity
module vaa522b #(
 parameter vfffc23 = 4'h0
) (
 output [3:0] vf3f282
);
 localparam p1 = vfffc23;
 wire [0:3] w0;
 assign vf3f282 = w0;
 v5253f2 #(
  .vc5c8ea(p1)
 ) vac1a49 (
  .v00a92d(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_0_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 0 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v5253f2 #(
 parameter vc5c8ea = 4'h0
) (
 output [3:0] v00a92d
);
 localparam p0 = vc5c8ea;
 wire [0:3] w1;
 assign v00a92d = w1;
 v5253f2_v465065 #(
  .V(p0)
 ) v465065 (
  .k(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante de 4 bits
/*-------------------------------------------------*/

module v5253f2_v465065 #(
 parameter V = 0
) (
 output [3:0] k
);
 assign k = V;
endmodule
//---- Top entity
module vc9d38c (
 input [3:0] vde0299,
 input [3:0] v72a4a4,
 output v97b3a2
);
 wire w0;
 wire w1;
 wire [0:3] w2;
 wire [0:3] w3;
 assign v97b3a2 = w0;
 assign w2 = vde0299;
 assign w3 = v72a4a4;
 v0ec077 vbd498e (
  .v25ee73(w0),
  .v4b5bc2(w1)
 );
 v69917e vd9b7af (
  .v6f3b5f(w1),
  .v199867(w2),
  .vad6846(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Distintos-4bit  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Comprobar si dos números de 4 bit son distintos
/*-------------------------------------------------*/
//---- Top entity
module v1ffaea #(
 parameter vfffc23 = 4'hA
) (
 output [3:0] vf3f282
);
 localparam p1 = vfffc23;
 wire [0:3] w0;
 assign vf3f282 = w0;
 v5253f2 #(
  .vc5c8ea(p1)
 ) vac1a49 (
  .v00a92d(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_10_4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 12 para bus de 4 bits
/*-------------------------------------------------*/
//---- Top entity
module v9274d3 #(
 parameter vc5c8ea = 0
) (
 output [3:0] v00a92d
);
 localparam p1 = vc5c8ea;
 wire [0:3] w0;
 assign v00a92d = w0;
 v9274d3_v465065 #(
  .VALUE(p1)
 ) v465065 (
  .k(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Constante-4bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor genérico constante, de 4 bits. Su valor se introduce como parámetro. Por defecto vale 0
/*-------------------------------------------------*/

module v9274d3_v465065 #(
 parameter VALUE = 0
) (
 output [3:0] k
);
 assign k = VALUE;
endmodule
//---- Top entity
module veebee1 (
 input [1:0] vc9d156,
 input [1:0] v340b68,
 input v50d6c6,
 output [1:0] v7fb9b3
);
 wire w0;
 wire [0:1] w1;
 wire [0:1] w2;
 wire [0:1] w3;
 assign w0 = v50d6c6;
 assign v7fb9b3 = w1;
 assign w2 = vc9d156;
 assign w3 = v340b68;
 veebee1_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i1(w2),
  .i0(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1 de 2 bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1 de 2 bits
/*-------------------------------------------------*/

module veebee1_ve4e0df (
 input [1:0] i1,
 input [1:0] i0,
 input sel,
 output [1:0] o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 2 bits
 
 reg [1:0] o;
 
 always @(*) begin
     case(sel)
         0: o = i0;
         1: o = i1;
         default: o = i0;
     endcase
 end
 
 
endmodule
//---- Top entity
module v945d5c #(
 parameter vfffc23 = 2
) (
 output [1:0] v2978f0
);
 localparam p1 = vfffc23;
 wire [0:1] w0;
 assign v2978f0 = w0;
 v157753 #(
  .vc5c8ea(p1)
 ) v9b88e7 (
  .v4ffce0(w0)
 );
endmodule

/*-------------------------------------------------*/
/*-- Valor_2_2bits  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Valor constante 2 para bus de 2 bits
/*-------------------------------------------------*/
//---- Top entity
module vb2090f (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 vb2090f_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- AND  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta AND
/*-------------------------------------------------*/

module vb2090f_vf4938a (
 input a,
 input b,
 output c
);
 //-- Puerta AND
 
 //-- module and (input wire a, input wire b,
 //--             output wire c);
 
 assign c = a & b;
 
 //-- endmodule
endmodule
//---- Top entity
module v35f267 (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v35f267_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NOT  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Puerta NOT
/*-------------------------------------------------*/

module v35f267_vd54ca1 (
 input a,
 output c
);
 //-- Puerta NOT
 
 //-- module (input wire a, output wire c);
 
 
 assign c = ~a;
 
 
 //-- endmodule
 
endmodule
//---- Top entity
module v5cc6ec (
 input vb186da,
 input v381ebf,
 input v50d6c6,
 output vc93bbe
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 assign w0 = v50d6c6;
 assign vc93bbe = w1;
 assign w2 = v381ebf;
 assign w3 = vb186da;
 v5cc6ec_ve4e0df ve4e0df (
  .sel(w0),
  .o(w1),
  .i0(w2),
  .i1(w3)
 );
endmodule

/*-------------------------------------------------*/
/*-- Mux 2 a 1  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Multiplexor de 2 a 1
/*-------------------------------------------------*/

module v5cc6ec_ve4e0df (
 input i1,
 input i0,
 input sel,
 output o
);
 //-- Multiplexor de 2 a 1, 
 //-- de 8 bits
 
 reg _o;
 
 always @(*) begin
     case(sel)
         0: _o = i0;
         1: _o = i1;
         default: _o = i0;
     endcase
 end
 
 assign o = _o;
 
endmodule
//---- Top entity
module vb4c12b #(
 parameter vb36a78 = "vb36a78.list"
) (
 input [3:0] v851180,
 output [4:0] vfde47f
);
 localparam p0 = vb36a78;
 wire [0:3] w1;
 wire [0:4] w2;
 assign w1 = v851180;
 assign vfde47f = w2;
 vb4c12b_v361fe9 #(
  .DATA(p0)
 ) v361fe9 (
  .i(w1),
  .q(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- mi-tabla4-5  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Circuito combinacional de 4 entradas y 5 salidas
/*-------------------------------------------------*/

module vb4c12b_v361fe9 #(
 parameter DATA = 0
) (
 input [3:0] i,
 output [4:0] q
);
 
 //-- Bits del bus de entrada
 localparam N = 4;
 
 //-- Bits del bus de salida
 localparam M = 5;
 
 //-- Calcular tamaño de la tabla
 //-- (filas) segun los bits de entrada
 localparam TAM = 2 ** N;
 
 //-- Definición de la tabla
 //-- Tabla de TAM elementos de M bits
 reg [M-1:0] tabla[0:TAM-1];
 
 //-- Read the table
 assign q = tabla[i];
 
 //-- Init table from DATA parameters
 initial begin
   if (DATA) $readmemb(DATA, tabla);
 end
endmodule
//---- Top entity
module v4798ba (
 input [4:0] v2f7f3b,
 output va8081e,
 output v84e765,
 output v185257,
 output ve17a78,
 output v6c3ff1
);
 wire [0:4] w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 assign w0 = v2f7f3b;
 assign v6c3ff1 = w1;
 assign ve17a78 = w2;
 assign v185257 = w3;
 assign v84e765 = w4;
 assign va8081e = w5;
 v4798ba_v5a7fc6 v5a7fc6 (
  .i(w0),
  .o0(w1),
  .o1(w2),
  .o2(w3),
  .o3(w4),
  .o4(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Separador-bus  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Separador de bus de 5-bits en 5 cables
/*-------------------------------------------------*/

module v4798ba_v5a7fc6 (
 input [4:0] i,
 output o4,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o4 = i[4];
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
